version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_root_username
      MONGO_INITDB_ROOT_PASSWORD: your_root_password
    networks:
      - mongo_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  mongodb_data:
  minio_data:

networks:
  mongo_network:
